### ISSUE TITLE
关于训练数据的问题

### ISSUE THREAD

**Issue by allenwangcheng** [MagicJackStone/FaceKit#95]
我想问下，widerface一共一万多张图，每一张都旋转360度可以得到360多万张图，这个量是不是太大了点，请问生成-180到180°的图片是随机选择旋转角度的，还是等间隔生成的，另外第一阶段的训练正负样本和中间样本大概都用到了多少的量啊，感觉生成的任意角度的数据有点多啊。

**Comment by Jack-CV** [comment]
你好，是每张图随机生成几个角度，没有生成360个那么多

**Comment by allenwangcheng** [comment]
> 你好，是每张图随机生成几个角度，没有生成360个那么多

你好，对widerface训练集有没有做过清洗，比如过滤掉模糊的图片，过滤掉标注不准确的图片等，第一阶段生成的正负样本的量级大概是多少

**Comment by Jack-CV** [comment]
@allenwangcheng 有的，根据wider face提供的label，过滤掉blur为2的，pose为1和2的

**Comment by allenwangcheng** [comment]
> @allenwangcheng 有的，根据wider face提供的label，过滤掉blur为2的，pose为1和2的

另外想问下，三个阶段的batch都是按照2：2：1吗，第一阶段的分类准确率和角度分类准确率大概分别是多少呢

**Comment by allenwangcheng** [comment]
还有三个任务的loss权重是多少啊，感觉这个很重要啊

**Comment by allenwangcheng** [comment]
第二个阶段通过第一个阶段做filter out the hard negative samples，这个具体是怎么做的呢，我很疑惑啊
